print(pcall(error, "error message"))